# Generated by Django 5.0.2 on 2024-02-11 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('ID_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('Especialidad', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Tarifa_por_sesion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Horarios_de_disponibilidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo_electronico', models.EmailField(max_length=254)),
                ('Contraseña', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=255)),
                ('Fecha_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('ID_turno', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_y_hora_del_turno', models.DateTimeField()),
                ('Estado_del_turno', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], max_length=20)),
                ('Mensaje_al_profesional', models.TextField(blank=True, null=True)),
                ('ID_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profesional')),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('ID_pago', models.AutoField(primary_key=True, serialize=False)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Metodo_de_pago', models.CharField(max_length=100)),
                ('Fecha_y_hora_del_pago', models.DateTimeField(auto_now_add=True)),
                ('ID_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.turno')),
            ],
        ),
        migrations.CreateModel(
            name='HistoralDeCitas',
            fields=[
                ('ID_historial', models.AutoField(primary_key=True, serialize=False)),
                ('Estado_anterior', models.CharField(max_length=20)),
                ('Estado_actual', models.CharField(max_length=20)),
                ('Fecha_y_hora_del_cambio_de_estado', models.DateTimeField(auto_now_add=True)),
                ('ID_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.turno')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='ID_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('ID_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('Contenido_del_mensaje', models.TextField()),
                ('Fecha_y_hora_del_mensaje', models.DateTimeField(auto_now_add=True)),
                ('ID_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.turno')),
                ('Destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='myapp.usuario')),
                ('Remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('ID_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('Puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('Comentario', models.TextField()),
                ('Fecha_de_la_valoracion', models.DateTimeField(auto_now_add=True)),
                ('ID_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.turno')),
            ],
        ),
    ]
